// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mcuqqiuhczkpzcpweozh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1jdXFxaXVoY3prcHpjcHdlb3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxOTE2OTQsImV4cCI6MjA3MDc2NzY5NH0.Gjo0jlXNrTtnYhtsY6c0nlv2LLEk9U58fUJ7n2Qx5t8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});